'spectralCrest',true,... 
'spectralDecrease',true,... 
'spectralEntropy',true,... 
'spectralFlatness',true,...
'spectralFlux',true,... 
'spectralCentroid',true,...
'spectralKurtosis',true,... 
'spectralRolloffPoint',true,... 
'spectralSkewness',true,... 
'spectralSlope',true,... 
'spectralSpread',true);

'linearSpectrum',true,...
'melSpectrum',true,... 
'barkSpectrum',true,... 
'erbSpectrum',true

'pitch',true,...
'mfcc',true,...
'mfccDelta',true,... 
'mfccDeltaDelta',true,...
'gtcc',true,...
'gtccDelta',true,... 
'gtccDeltaDelta',true,... 
'harmonicRatio',true);